# Generated by Django 3.1.7 on 2023-01-26 18:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iva_preorder', models.DecimalField(decimal_places=2, max_digits=5)),
                ('full_name', models.CharField(max_length=255)),
                ('rif', models.CharField(max_length=25)),
                ('rif_types', models.CharField(choices=[('V', 'V'), ('J', 'J'), ('G', 'G'), ('E', 'E'), ('P', 'P')], default='V', max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('address_line', models.CharField(max_length=255)),
                ('identification', models.IntegerField()),
                ('identification_types', models.CharField(choices=[('V', 'V'), ('E', 'E'), ('P', 'P')], default='V', max_length=10)),
                ('state_province_region', models.CharField(max_length=255)),
                ('postal_zip_code', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=255)),
                ('shipping_branch', models.CharField(choices=[('Valencia', 'Carabobo - Multimax Valencia'), ('Los Guayos', 'Carabobo - Multimax Los Guayos'), ('Caracas', 'Caracas - Multimax Los Ilustres'), ('Caracas_2', 'Caracas - Multimax Los Cortijos'), ('Caracas_3', 'Caracas - Multimax Express La Candelaria')], default='Carabobo - Multimax Valencia', max_length=255)),
                ('date_issued', models.DateTimeField(default=datetime.datetime.now)),
                ('transaction_type', models.CharField(choices=[('Transferencia', 'Transferencia Banesco - Banesco en bolivares'), ('Pago movil', 'Pago móvil'), ('Transferencia dolares nacional', 'Transferencia Banesco - Banesco en dolares nacional'), ('Transferencia dolares internacional', 'Tarjetas de crédito internacional'), ('Paypal', 'Paypal')], default='Transferencia Banesco - Banesco en bolivares', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField()),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preorders.preorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
    ]
