# Generated by Django 3.1.7 on 2023-01-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='identification',
            field=models.CharField(max_length=255),
        ),
    ]
