# Generated by Django 3.1.7 on 2023-06-04 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preorders', '0002_preorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 23, 16, 50, 43526, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='preorderitem',
            name='count',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='preorderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='preorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
